In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

import sklearn.metrics
from sklearn.preprocessing import StandardScaler

import itertools
import scipy
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import sklearn
print('The scikit-learn version is {}.'.format(sklearn.__version__))

The scikit-learn version is 0.21.2.


In [3]:
df = pd.read_csv('http://localhost:8888/edit/Downloads/OJ.csv')
df.info()
df.head(15)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 12, saw 2


In [64]:
%matplotlib inline

data_url="/Users/monalisa/Downloads/OJ.csv"
data=pd.read_csv(data_url)
print(data.head())


   Unnamed: 0 Purchase  WeekofPurchase  StoreID  PriceCH  PriceMM  DiscCH  \
0           1       CH             237        1     1.75     1.99    0.00   
1           2       CH             239        1     1.75     1.99    0.00   
2           3       CH             245        1     1.86     2.09    0.17   
3           4       MM             227        1     1.69     1.69    0.00   
4           5       CH             228        7     1.69     1.69    0.00   

   DiscMM  SpecialCH  SpecialMM   LoyalCH  SalePriceMM  SalePriceCH  \
0     0.0          0          0  0.500000         1.99         1.75   
1     0.3          0          1  0.600000         1.69         1.75   
2     0.0          0          0  0.680000         2.09         1.69   
3     0.0          0          0  0.400000         1.69         1.69   
4     0.0          0          0  0.956535         1.69         1.69   

   PriceDiff Store7  PctDiscMM  PctDiscCH  ListPriceDiff  STORE  
0       0.24     No   0.000000   0.000000   

In [66]:
X=data.iloc[:, :-1].values
y=data.iloc[:, 18].values
print (y)


[1 1 1 ... 0 0 1]


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=42, criterion="entropy",
                             max_depth=3, max_leaf_nodes=5)
clf.fit(X_train, y_train)

y_pred_dt = clf.predict(X_test)

ValueError: could not convert string to float: 'CH'

In [10]:
sc_X=StandardScaler()
X_train=Sc

NameError: name 'Sc' is not defined

In [11]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

ValueError: could not convert string to float: 'CH'

In [70]:
#Encoding categorical data

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])
X[:,14] = le.fit_transform(X[:,14])
print(X)



[[1 0 237 ... 0.0 0.0 0.24]
 [2 0 239 ... 0.150754 0.0 0.24]
 [3 0 245 ... 0.0 0.09139800000000001 0.23]
 ...
 [1068 1 257 ... 0.0 0.0 0.32]
 [1069 0 261 ... 0.112676 0.0 0.27]
 [1070 0 270 ... 0.0 0.0 0.32]]


In [71]:
le_y=LabelEncoder()
y=le_y.fit_transform(y)

In [72]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

ValueError: could not convert string to float: 'CH'

In [73]:
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier(random_state=42, criterion="entropy",
                             max_depth=3, max_leaf_nodes=5)
clf.fit(X_train, y_train)

y_pred_dt = clf.predict(X_test)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=3,
                       max_features=None, max_leaf_nodes=5,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=42, splitter='best')

In [54]:
clf.predict_proba([[2, 2]])
clf.predict([[2, 2]])

ValueError: Number of features of the model must match the input. Model n_features is 18 and input n_features is 2 

In [75]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_dt)

array([[71,  0,  0,  0,  0],
       [ 0, 29,  0,  0,  0],
       [ 0,  0, 51,  0,  0],
       [ 0,  0,  0, 36,  0],
       [ 0,  0,  0,  0, 27]])

In [77]:

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_dt,))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        71
           1       1.00      1.00      1.00        29
           2       1.00      1.00      1.00        51
           3       1.00      1.00      1.00        36
           4       1.00      1.00      1.00        27

    accuracy                           1.00       214
   macro avg       1.00      1.00      1.00       214
weighted avg       1.00      1.00      1.00       214

